name: hipo-win-conda

on: [push, pull_request]

jobs:
  release:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest]

    steps:
      - uses: actions/checkout@v4

      - name: Setup Conda
        uses: conda-incubator/setup-miniconda@v2

      - name: Install GKlib via Conda
        run: |
          conda install -y -c conda-forge gklib
          conda activate test

      - name: LS
        shell: bash
        run: |
          ls C:\Users\runneradmin\conda_pkgs_dir

      # - name: Check installs 
      #   working-directory: ${{runner.workspace}}
      #   run: |
      #     cd installs
      #     ls 
      #     ls lib

      # - name: Copy GKlib shared (bug)
      #   working-directory: ${{runner.workspace}}
      #   run: |
      #     cd installs
      #     cd lib
      #     ln libGKlib.so.0 libGKlib.so
      #     ls 

      - name: Install METIS
        run: |
          conda install -y -c conda-forge metis

      - name: Install OpenBLAS
        run: |
          conda install -y -c conda-forge openblas

      - name: Create build dir
        working-directory: ${{runner.workspace}}
        shell: bash
        run: mkdir build

      - name: Configure cmake
        shell: bash
        working-directory: ${{runner.workspace}}/build
        run: |
          cmake $GITHUB_WORKSPACE \
          -DHIPO=ON \
          -DCMAKE_FIND_LIBRARY_PREFIXES=";lib"

      - name: Build 
        shell: bash
        working-directory: ${{runner.workspace}}/build
        run: |
          cmake --build . --parallel --config Release

      - name: Test executable 
        shell: bash
        working-directory: ${{runner.workspace}}/build
        run: ./Release/bin/highs --solver=hipo $GITHUB_WORKSPACE/check/instances/afiro.mps

      - name: Ctest
        shell: bash
        working-directory: ${{runner.workspace}}/build
        run: |
          ctest --parallel --timeout 300 --output-on-failure -C Release

  # debug:
  #   runs-on: ${{ matrix.os }}
  #   strategy:
  #     fail-fast: false
  #     matrix:
  #       os: [windows-latest]

  #   steps:
  #     - uses: actions/checkout@v4

  #     - name: Install METIS
  #       run: vcpkg install metis

  #       # run: ls C:/vcpkg/packages/metis_x64-windows/
  #       # run: ls C:/vcpkg/packages/metis_x64-windows/lib
  #       # run: ls C:/vcpkg/packages/metis_x64-windows/share
  #       # run: ls C:/vcpkg/packages/gklib_x64-windows/share/gklib

  #     - name: Install OpenBLAS
  #       run: vcpkg install openblas

  #     - name: Create build dir
  #       run: cmake -E make_directory ${{runner.workspace}}/build

  #     - name: Configure cmake
  #       shell: bash
  #       working-directory: ${{runner.workspace}}/build
  #       # Here is _DIR because with vcpkg CMake find_package works.
  #       run: |
  #         cmake $GITHUB_WORKSPACE \
  #         -DHIPO=ON \
  #         -Dmetis_DIR=C:/vcpkg/packages/metis_x64-windows/share/metis \
  #         -DGKlib_DIR=C:/vcpkg/packages/gklib_x64-windows/share/gklib \
  #         -DOpenBLAS_DIR=C:/vcpkg/packages/openblas_x64-windows/share/openblas

  #     - name: Build 
  #       shell: bash
  #       working-directory: ${{runner.workspace}}/build
  #       run: |
  #         cmake --build . --parallel --config Debug

  #     - name: Test executable 
  #       shell: bash
  #       working-directory: ${{runner.workspace}}/build
  #       run: ./Debug/bin/highs --solver=hipo $GITHUB_WORKSPACE/check/instances/afiro.mps

  #     - name: Ctest
  #       shell: bash
  #       working-directory: ${{runner.workspace}}/build
  #       run: |
  #         ctest --parallel --timeout 300 --output-on-failure -C Debug