name: hipo

on: [push, pull_request]

jobs:
  windows_debug:
    runs-on: [windows-latest]
    strategy:
      fail-fast: false
      matrix:
        config: [Debug]
        all_tests: [ON]
        arch: ["x64"]

    steps:
      - uses: actions/checkout@v4

      - name: Configure CMake
        shell: pwsh
        run: |
          cmake `
          -S "$env:GITHUB_WORKSPACE" `
          -B "${{ runner.workspace }}/build" `
          -A ${{ matrix.arch }} `
          -DHIPO=ON `
          -DALL_TESTS=${{ matrix.all_tests }} `
          -DBUILD_OPENBLAS=ON

      - name: Build
        shell: pwsh
        working-directory: ${{runner.workspace}}/build
        run: |
          cmake --build . --parallel --config ${{ matrix.config }}

      - name: Test executable
        shell: pwsh
        working-directory: ${{runner.workspace}}/build
        run: |
          & ".\${{ matrix.config }}\bin\highs.exe" --solver=hipo `
          "$env:GITHUB_WORKSPACE/check/instances/afiro.mps"

      - name: Ctest
        shell: pwsh
        working-directory: ${{runner.workspace}}/build
        run: |
          & ".\${{ matrix.config }}\bin\unit_tests.exe" "[qpsolver]" -s
          