name: test-python-macos

on: [push, pull_request]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest]
        python: [3.12]
    steps:
      - uses: actions/checkout@v4
      - name: Install correct python version
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python }}

      - name: Install build dependencies
        run: python3 -m pip install numpy wheel pytest

      - name: Test Python Interface
        run: |
          python3 -m pip install .
          pytest -v -k "not test_hipo"

      - name: Test Python Examples
        run: |
         python3 ./examples/call_highs_from_python_highspy.py
         python3 ./examples/call_highs_from_python_mps.py
         python3 ./examples/call_highs_from_python.py
         python3 ./examples/minimal.py

  build_hipo:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest]
        python: [3.12]
    steps:
      - uses: actions/checkout@v4
      - name: Install correct python version
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python }}

      - name: Edit pyproject
        run: |
          ls
          METIS_ROOT="${{ runner.workspace }}/installs"
          sed -i '' '/cmake\.args = \[/,/\]/{
            s|"-DPYTHON_BUILD_SETUP=ON"|"-DPYTHON_BUILD_SETUP=ON",\
            "-DHIPO=ON"|
          }' pyproject.toml
          cat pyproject.toml

      - name: Install build dependencies
        run: python3 -m pip install numpy wheel pytest

      - name: Test Python Interface
        run: |
          python3 -m pip install .
          pytest

      - name: Test Python Examples
        run: |
         python3 ./examples/call_highs_from_python_highspy.py
         python3 ./examples/call_highs_from_python_mps.py
         python3 ./examples/call_highs_from_python.py
         python3 ./examples/minimal.py